name: flutter_getx_mvc_architecture_guide
description: "Guide: MVC Architecture with GetX State Management"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # State Management
  get: ^4.6.6
  
  # HTTP Client
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
